apiVersion: v1
kind: Service
metadata:
  name: mypython-svc
  namespace: xxx
  labels:
    app: mypython
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    app: mypython
