FROM nginx:1.15.5-alpine
MAINTAINER xuxiaoqiang <xuxiaoqiang@baidu.com>

ADD nginx.conf /etc/nginx/
ADD upstream.conf /etc/nginx/custom/
ADD css /www/css
ADD html /www/html
ADD index.html /www/
ADD images /www/images
ADD js /www/js

