apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myphp-green
  namespace: xxx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myphp
        track: stable
        version: 2.0.0
    spec:
      containers:
        - name: myphp
          image: "hub.baidubce.com/bootcamp/myphp:2.0.0"
          ports:
            - name: http
              containerPort: 80
