apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myphp-canary
  namespace: xxx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myphp
        track: canary
        version: 2.0.0
    spec:
      containers:
        - name: hello
          image: "hub.baidubce.com/bootcamp/myphp:2.0.0"
          ports:
            - name: http
              containerPort: 80