apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-house-dep
  labels: 
    app: backend-house
spec:
  selector:
    matchLabels:
      app: backend-house
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-house
    spec:
      containers:
        - name: backend-house
          image: hub.baidubce.com/bootcamp/backend-house
          env:
          - name: VM_OPTIONS
            value: "-Xms64m -Xmx64m"
          - name: mysql_password
            valueFrom:
              secretKeyRef:
                name: user-password
                key: password
          volumeMounts:
          - name: config
            mountPath: "/app/config/"
            readOnly: true
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
      volumes:
        - name: config
          configMap:
            name: backend-conf
            items:
            - key: application.properties 
              path: application.properties

---

apiVersion: v1
kind: Service
metadata:
  name: backend-house-svc
  labels: 
    app: backend-house
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend-house
  
