apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-house-dep
  labels: 
    app: mysql-house
spec:
  selector:
    matchLabels:
      app: mysql-house
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-house
    spec:
      containers:
        - name: mysql-house
          image: hub.baidubce.com/bootcamp/mysql-house
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-password
                key: password
          ports:
            - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-house-svc
  labels: 
    app: mysql-house
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-house
  