# create a secret named `user-password` and it has two values
# username = root
# password = root123!

apiVersion: v1
kind: Secret
metadata:
  name: user-password
type: Opaque
data:
  username: cm9vdA==
  password: cm9vdDEyMyE=
