apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: liveness-tcp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: liveness-tcp
        track: stable
        version: 1.0.0
    spec:
      containers:
        - name: liveness-tcp
          image: "hub.baidubce.com/bootcamp/liveness-tcp:1.0.0"
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8090
            initialDelaySeconds: 15
            periodSeconds: 20
