apiVersion: v1
kind: Service
metadata:
  name: myprobe-svc-http
  labels:
    app: readiness-http
spec:
  ports:
  - port: 8081
    targetPort: 8080
  type: NodePort
  selector:
    app: readiness-http
