apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mytomcat-green
  namespace: xxx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mytomcat
        track: stable
        version: 2.0.0
    spec:
      containers:
        - name: mytomcat
          image: "hub.baidubce.com/bootcamp/mytomcat:2.0.0"
          ports:
            - name: http
              containerPort: 8080
