apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytomcat
spec:
  selector:
    matchLabels:
      app: mytomcat
  template:
    metadata:
      labels:
        app: mytomcat
        version: "1.0"
    spec:
      containers:
      - name: mytomcat
        image: "tanzhongyibidu/mytomcat:1.0"
        ports:
        - containerPort: 8080

