apiVersion: v1
kind: Service
metadata:
  name: mynode-svc
  labels:
    app: mynode
spec:
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    app: mynode
    version: "2.0"

