apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mynode-canary
  namespace: xxx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mynode
        track: canary
        version: 2.0.0
    spec:
      containers:
        - name: hello
          imagePullPolicy: Always
          image: "hub.baidubce.com/bootcamp/mynode:2.0.0"
          ports:
            - name: http
              containerPort: 8080